export const CREATE_TODO = "CREATE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const GET_TODO = "GET_TODO";

export const CREATE_TODO_REQUESTED = "CREATE_TODO_REQUESTED";
export const CREATE_TODO_SUCCEEDED = "CREATE_TODO_SUCCEEDED";
export const CREATE_TODO_FAILED = "CREATE_TODO_FAILED";

export const TOGGLE_TODO_REQUESTED = "TOGGLE_TODO_REQUESTED";
export const TOGGLE_TODO_SUCCEEDED = "TOGGLE_TODO_SUCCEEDED";
export const TOGGLE_TODO_FAILED = "TOGGLE_TODO_FAILED";

export const DELETE_TODO_REQUESTED = "DELETE_TODO_REQUESTED";
export const DELETE_TODO_SUCCEEDED = "DELETE_TODO_SUCCEEDED";
export const DELETE_TODO_FAILED = "DELETE_TODO_FAILED";

export const UPDATE_TODO_REQUESTED = "UPDATE_TODO_REQUESTED";
export const UPDATE_TODO_SUCCEEDED = "UPDATE_TODO_SUCCEEDED";
export const UPDATE_TODO_FAILED = "UPDATE_TODO_FAILED";

export const GET_TODO_REQUESTED = "GET_TODO_REQUESTED";
export const GET_TODO_SUCCEEDED = "GET_TODO_SUCCEEDED";
export const GET_TODO_FAILED = "GET_TODO_FAILED";

export const GOTO_DETAIL = "GOTO_DETAIL";
